final featuredproducts = [
  {
    'id': '0',
    'title': 'Levi\'s T-Shirt',
    'price': 35.98,
    'imageUrl': 'assets/images/clothe2.png',
    'company': 'Levi\'s',
    'sizes': [36, 38, 40],
    'category':'clothes',
  },
  {
    'id': '1',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
    'category':'shoes',
  },
  {
    'id': '2',
    'title': 'Frying Pan',
    'price': 8.75,
    'imageUrl': 'assets/images/utensil3.png',
    'company': 'Chammach Katori',
    'sizes': [8, 9, 10],
    'category':'utensils',
  },
  {
    'id': '3',
    'title': 'Samsung Galaxy A52',
    'price': 500.00,
    'imageUrl': 'assets/images/electronic1.png',
    'company': 'Samsung',
    'category':'electronics',
    'colors': ['Black', 'White', 'Blue', 'Silver'],
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '4',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
    'category':'shoes',
  },
  {
    'id': '5',
    'title': 'Cooker',
    'price': 23.00,
    'imageUrl': 'assets/images/utensil1.png',
    'company': 'Pigeon',
    'sizes': [9, 10, 11, 12],
    'category':'utensils',
  },
  {
    'id': '6',
    'title': 'HP Victus',
    'price': 1100.00,
    'imageUrl': 'assets/images/electronic3.png',
    'company': 'HP',
    'colors': ['Black', 'White', 'Grey'],
    'category':'electronics',
    'sizes': [9, 10, 11, 12],
  },
];

final shoeproducts = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoes_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
    'category':'shoes',
  },
  {
    'id': '1',
    'title': 'Adidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoes_2.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
    'category':'shoes',
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoes_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
    'category':'shoes',
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoes_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
    'category':'shoes',
  },
];

final clotheproducts = [
  {
    'id': '0',
    'title': 'Women\'s Frock',
    'price': 20.00,
    'imageUrl': 'assets/images/clothe1.png',
    'company': 'Zara',
    'sizes': [34, 36, 38, 40],
    'category':'clothes',
  },
  {
    'id': '1',
    'title': 'Levi\'s T-Shirt',
    'price': 35.98,
    'imageUrl': 'assets/images/clothe2.png',
    'company': 'Levi\'s',
    'sizes': [36, 38, 40],
    'category':'clothes',
  },
  {
    'id': '2',
    'title': 'Men\'s Beach Shirt',
    'price': 25.64,
    'imageUrl': 'assets/images/clothe3.png',
    'company': 'Wrogn',
    'sizes': [34, 36, 40],
    'category':'clothes',
  },
  {
    'id': '3',
    'title': 'Lee Jeans',
    'price': 40.08,
    'imageUrl': 'assets/images/clothe4.png',
    'company': 'Lee',
    'sizes': [30, 34, 36],
    'category':'clothes',
  },
];

final electronicproducts = [
  {
    'id': '0',
    'title': 'Samsung Galaxy A52',
    'price': 500.00,
    'imageUrl': 'assets/images/electronic1.png',
    'company': 'Samsung',
    'category':'electronics',
    'colors': ['Black', 'White', 'Blue', 'Silver'],
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'I-phone 14',
    'price': 660.00,
    'imageUrl': 'assets/images/electronic2.png',
    'company': 'Apple',
    'category':'electronics',
    'colors': ['Black', 'White', 'Blue', 'Pink'],
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '2',
    'title': 'HP Victus',
    'price': 1100.00,
    'imageUrl': 'assets/images/electronic3.png',
    'company': 'HP',
    'colors': ['Black', 'White', 'Grey'],
    'category':'electronics',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': 'Usha Press',
    'price': 15.15,
    'imageUrl': 'assets/images/electronic4.png',
    'company': 'Usha',
    'colors': ['Black', 'White', 'Blue'],
    'category':'electronics',
    'sizes': [9, 10, 11, 12],
  },
];

final utensilproducts = [
  {
    'id': '0',
    'title': 'Cooker',
    'price': 23.00,
    'imageUrl': 'assets/images/utensil1.png',
    'company': 'Pigeon',
    'sizes': [9, 10, 11, 12],
    'category':'utensils',
  },
  {
    'id': '1',
    'title': 'Fork',
    'price': 3.50,
    'imageUrl': 'assets/images/utensil2.png',
    'company': 'Nayasa',
    'sizes': [9, 10, 12],
    'category':'utensils',
  },
  {
    'id': '2',
    'title': 'Frying Pan',
    'price': 8.75,
    'imageUrl': 'assets/images/utensil3.png',
    'company': 'Chammach Katori',
    'sizes': [8, 9, 10],
    'category':'utensils',
  },
  {
    'id': '3',
    'title': 'Bowl',
    'price': 12.95,
    'imageUrl': 'assets/images/utensil4.png',
    'company': 'Chammach Kartori',
    'sizes': [8, 9, 10],
    'category':'utensils',
  },
];

