// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzWWeH1H6pLwSAt5PVVrETiZ75yDGjjus',
    appId: '1:12182895605:web:55c187b39613e37a0a7ebc',
    messagingSenderId: '12182895605',
    projectId: 'my-emart-app',
    authDomain: 'my-emart-app.firebaseapp.com',
    storageBucket: 'my-emart-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHA9AmLku8CkNc68WHYPLEmaAtYmQ80ts',
    appId: '1:12182895605:android:fb5abded06a2275a0a7ebc',
    messagingSenderId: '12182895605',
    projectId: 'my-emart-app',
    storageBucket: 'my-emart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4QTFdE4CLvftcrqFdVd31rkJmoEMzLw',
    appId: '1:12182895605:ios:0fa724da68f23e450a7ebc',
    messagingSenderId: '12182895605',
    projectId: 'my-emart-app',
    storageBucket: 'my-emart-app.appspot.com',
    iosBundleId: 'com.example.flipkart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4QTFdE4CLvftcrqFdVd31rkJmoEMzLw',
    appId: '1:12182895605:ios:0fa724da68f23e450a7ebc',
    messagingSenderId: '12182895605',
    projectId: 'my-emart-app',
    storageBucket: 'my-emart-app.appspot.com',
    iosBundleId: 'com.example.flipkart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzWWeH1H6pLwSAt5PVVrETiZ75yDGjjus',
    appId: '1:12182895605:web:c8cb82e31d0bd8960a7ebc',
    messagingSenderId: '12182895605',
    projectId: 'my-emart-app',
    authDomain: 'my-emart-app.firebaseapp.com',
    storageBucket: 'my-emart-app.appspot.com',
  );
}
